### PR TITLE
NavigationBar + HomePags(Scrolling Photos)

### PR DESCRIPTION
**Pull request by jessicamaximo23**
I started by creating the nav bar and decided to make a carousel of photos scrolling on the home page, as I've never done before, I'll study the best way to do it and upload it again if it works.

### CODE REVIEW

**Comment by JulienVillanti** [comment]
Looks good, I will try to create the Login page and I'm also looking into adding a location banner that would show all the clinic's location, seems like it is not as straightforward as I thought it would be though! We will see!

**Comment by JulienVillanti** [comment]
The carousel is really nice, sorry I haven't done much! I'll try to check
if we can put the locations of the clinics on a Google map in the Contact
us section

**Comment by jessicamaximo23** [comment]
I thought the same thing about Google Maps, I'll definitely add it later and I'll even improve the footer.
If you have another good idea let me know.

Don't worry, we have enough time to build calmly, Wandrey probably hasn't even started hahahah

**Comment by JulienVillanti** [comment]
Still better start early, I think the login authentication with firebase
might cause us some trouble. Also we'll talk about it but let me know if
you'd prefer the login container to be bigger or if it is fine like that.
Did you look online for creating the carousel or you did it yourself?

**Comment by jessicamaximo23** [comment]
I'll check,but feel free for do the way that you want.

I wish I could do this alone 🤭, but it was impossible for me! I used a You Tube video lesson, a tutorial and GPT.

**Pull request merged**
